// Map is an 8x10 grid.
// Inventory is a vertical column 2 cells wide.
var X = 10;
var Y = 8;
var INVENTORY_X = 2;

var MOVEMENTS_PER_FALL = 4;
var MOVEMENTS_PER_WALK = 2;
var MOVEMENTS_PER_VERTICAL_MOVEMENT = 1;
var MOVEMENTS_PER_CELL = 40;

var TOTAL_X = X + INVENTORY_X;

var MOVEMENTS = {
    FALL: 'fall',
    WALK: 'walk',
    MOVE_VERTICALLY: 'moveVertically'
};

module.exports = {
    X: X,
    Y: Y,
    TOTAL_X: TOTAL_X,
    MOVEMENTS_PER_FALL: MOVEMENTS_PER_FALL,
    MOVEMENTS_PER_WALK: MOVEMENTS_PER_WALK,
    MOVEMENTS_PER_VERTICAL_MOVEMENT: MOVEMENTS_PER_VERTICAL_MOVEMENT,
    MOVEMENTS_PER_CELL: MOVEMENTS_PER_CELL,
    MOVEMENTS: MOVEMENTS
};
