// Map is a XxY grid.
var X = 10;
var Y = 8;
var INVENTORY_X = 2;

var FALLS_PER_CELL = 4;
var WALKS_PER_CELL = 2;
var VERTICAL_MOVEMENTS_PER_CELL = 1;
var MOVEMENTS_PER_CELL = 40;

var TOTAL_X = X + INVENTORY_X;

var MOVEMENTS = {
    FALL: 'fall',
    WALK: 'walk',
    MOVE_VERTICALLY: 'moveVertically'
};

module.exports = {
    X: X,
    Y: Y,
    TOTAL_X: TOTAL_X,
    FALLS_PER_CELL: FALLS_PER_CELL,
    WALKS_PER_CELL: WALKS_PER_CELL,
    VERTICAL_MOVEMENTS_PER_CELL: VERTICAL_MOVEMENTS_PER_CELL,
    MOVEMENTS_PER_CELL: MOVEMENTS_PER_CELL,
    MOVEMENTS: MOVEMENTS
};
